myfreelance_type_index:
    path:     /
    defaults: { _controller: "MyfreelanceBundle:Type:index" }
    methods:  GET

myfreelance_type_show:
    path:     /{id}/show
    defaults: { _controller: "MyfreelanceBundle:Type:show" }
    methods:  GET

myfreelance_type_new:
    path:     /new
    defaults: { _controller: "MyfreelanceBundle:Type:new" }
    methods:  [GET, POST]

myfreelance_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyfreelanceBundle:Type:edit" }
    methods:  [GET, POST]

myfreelance_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyfreelanceBundle:Type:delete" }
    methods:  [DELETE,GET]
