services:
    myfreelance.twig.facebook_extension:
        class: MyfreelanceBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }
    
#    myfreelance.form.ticket_customer_type:
#        class : MyfreelanceBundle\Form\Customer\TicketCustomerType
#        arguments :
#            $entityManager : "@doctrine.orm.entity_manager"
#            
#    myfreelance.user_manipulator:
#        class: MyfreelanceBundle\Tools\UserManipulator
#        arguments: ["@fos_user.user_manager"]
#    myfreelance.example:
#        class: MyfreelanceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
