<?php

namespace MyfreelanceBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function qbGoToTheBill(){
        $qb = $this->createQueryBuilder('t');
        $qb->leftJoin('t.state', 's');
        $qb->leftJoin('t.bill','b');
        $qb->where($qb->expr()->andX($qb->expr()->like('s.name','?1')),"b.id IS NULL")
                ->setParameter(1, 'fini');
        
        return $qb;
    }
    
    public function findByUser(\MyfreelanceBundle\Entity\User $user){
        if(!($user instanceof \MyfreelanceBundle\Entity\Provider))
            throw new Exception("User is not Provider");
        
        $qb = $this->createQueryBuilder('t');
        
        $qb->leftJoin('t.project','p')
                ->leftJoin('p.customer','c')
                ->leftJoin('c.provider', 'prov')
                ->where($qb->expr()->eq('prov.id',"?1"));
        $qb->setParameter(1, $user->getId());
        
        return $qb->getQuery()->getResult();
        
    }
}
